### ISSUE TITLE
I would like to contribute to this Pattern.

### ISSUE THREAD

**Issue by jrspinella** [Azure/terraform-azurerm-avm-ptn-hubnetworking#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We currently have a Hub Networking module that uses the AVM modules. I would like to see if we can integrate our stuff into this module. We follow SCCA compliance for our government customers, but I think we can make it work.

check out our module at [https://github.com/azurenoops/terraform-azurerm-overlays-management-hub](https://github.com/azurenoops/terraform-azurerm-overlays-management-hub)

I also would like to know how you are going to handle spokes in a Hub/Spoke pattern?

### New or Affected Resource(s)/Data Source(s)

n/a

**Comment by matt-FFFFFF** [comment]
Hi @jrspinella now that we have the initial version here please feel free to reach out to me, raise issues and make PRs

**Comment by matt-FFFFFF** [comment]
Spokes are handled by the lz-vending module btw
